name: valgrind tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: into repo files
        uses: actions/checkout@v3

      - name: get Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: build
        run: make

      - name: Valgrind output
        run: make test
